name: "GitHub Changelog Generator"
description: "Automatically generate change log from your tags, issues, labels and pull requests on GitHub."
branding:
  icon: edit
  color: orange
inputs:
  repo:
    description: "Target GitHub repo in the form of organization/repository."
    required: false
  user:
    description: "Username of the owner of target GitHub repo."
    required: false
  project:
    description: "Name of project on GitHub."
    required: false
  token:
    description: "To make more than 50 requests per hour your GitHub token is required."
    required: false
  date_format:
    description: "Date format."
    required: false
  output:
    description: "Output file."
    required: false
  base:
    description: "Optional base file to append generated changes to."
    required: false
  header-label:
    description: "Set up custom header label."
    required: false
  configure-sections:
    description: "Define your own set of sections which overrides all default sections."
    required: false
  add-sections:
    description: "Add new sections but keep the default sections."
    required: false
  front-matter:
    description: "Add YAML front matter. Formatted as JSON because it's easier to add on the command line."
    required: false
  issues:
    description: "Include closed issues in changelog."
    required: false
  issues-wo-labels:
    description: "Include closed issues without labels in changelog."
    required: false
  pull-requests:
    description: "Include pull-requests in changelog."
    required: false
  pr-wo-labels:
    description: "Include pull requests without labels in changelog."
    required: false
  filter-by-milestone:
    description: "Use milestone to detect when issue was resolved."
    required: false
  author:
    description: "Add author of pull request at the end."
    required: false
  usernames-as-github-logins:
    description: "Use GitHub tags instead of Markdown links for the author of an issue or pull-request."
    required: false
  unreleased-only:
    description: "Generate log from unreleased closed issues only."
    required: false
  unreleased:
    description: "Add to log unreleased closed issues."
    required: false
  unreleased-label:
    description: "Include compare link (Full Changelog) between older version and newer version."
    required: false
  include-labels:
    description: "Of the labeled issues, only include the ones with the specified labels."
    required: false
  exclude-labels:
    description: "Issues with the specified labels will be excluded from changelog."
    required: false
  issue-line-labels:
    description: "The specified labels will be shown in brackets next to each matching issue. Use \"ALL\" to show all labels."
    required: false
  exclude-tags:
    description: "Changelog will exclude specified tags."
    required: false
  exclude-tags-regex:
    description: "Apply a regular expression on tag names so that they can be excluded."
    required: false
  since-tag:
    description: "Changelog will start after specified tag (default: last tag)."
    default: "'$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)'"
    required: false
  due-tag:
    description: "Changelog will end before specified tag."
    required: false
  max-issues:
    description: "Maximum number of issues to fetch from GitHub."
    required: false
  release-url:
    description: "The URL to point to for release links, in printf format (with the tag as variable)."
    required: false
  github-site:
    description: "The Enterprise GitHub site where your project is hosted."
    required: false
  github-api:
    description: "The enterprise endpoint to use for your GitHub API."
    required: false
  simple-list:
    description: "Create a simple list from issues and pull requests."
    required: false
  future-release:
    description: "Put the unreleased changes in the specified release number."
    required: false
  release-branch:
    description: "Limit pull requests to the release branch, such as master or release."
    required: false
  http-cache:
    description: "Use HTTP Cache to cache GitHub API requests (useful for large repos)."
    required: false
  cache-file:
    description: "Filename to use for cache."
    required: false
  cache-log:
    description: "Filename to use for cache log."
    required: false
  ssl-ca-file:
    description: "Path to cacert.pem file."
    required: false
  #  require: # excluded
  verbose:
    description: "Run verbosely."
    required: false
  #  version: # excluded
  #  help: # excluded
  breaking-label:
    description: "Set up custom label for breaking changes section."
    required: false
  breaking-labels:
    description: "Issues with these labels will be added to a new section, called \"Breaking changes\"."
    required: false
  enhancement-label:
    description: "Set up custom label for enhancements section."
    required: false
  enhancement-labels:
    description: "Issues with the specified labels will be added to \"Implemented enhancements\" section."
    required: false
  bugs-label:
    description: "Set up custom label for bug-fixes section."
    required: false
  bug-labels:
    description: "Issues with the specified labels will be added to \"Fixed bugs\" section."
    required: false
  deprecated-label:
    description: "Set up custom label for deprecated section."
    required: false
  deprecated-labels:
    description: "Issues with the specified labels will be added to a section called \"Deprecated\"."
    required: false
  removed-label:
    description: "Set up custom label for removed section."
    required: false
  removed-labels:
    description: "Issues with the specified labels will be added to a section called \"Removed\"."
    required: false
  security-label:
    description: "Set up custom label for security section."
    required: false
  security-labels:
    description: "Issues with the specified labels will be added to a section called \"Security fixes\"."
    required: false
  issues-label:
    description: "Set up custom label for closed-issues section."
    required: false
  pr-label:
    description: "Set up custom label for pull requests section."
    required: false
outputs:
  changelog:
    description: "Contents of generated change log."
runs:
  using: "docker"
  image: "Dockerfile"
