name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "✏️ Generate full changelog"
        id: generate-full-changelog
        uses: heinrichreimer/action-github-changelog-generator@{{ github.sha }}
      - name: "📤 Upload changelog"
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "Changelog"
          path: CHANGELOG.md
